In [1]:
import pandas as pd

from utils.df_loader import load_adult_df
from utils.preprocessing import remove_missing_values

pd.options.mode.chained_assignment = None 

In [2]:
df, feature_names, numerical_cols, categorical_cols, columns_type, target_name, possible_outcomes = load_adult_df()

In [3]:
from sklearn.tree import DecisionTreeClassifier

In [5]:
from utils.preprocessing import label_encode
from sklearn.model_selection import train_test_split

In [6]:
enconded_df, encoder_dict = label_encode(df, categorical_cols)

In [7]:
train_df, test_df = train_test_split(enconded_df, train_size=.8, random_state=123, shuffle=True)

In [45]:
import numpy as np
import pickle
X_train = np.array(train_df[feature_names])
y_train = np.array(train_df[target_name])


In [20]:
dt = DecisionTreeClassifier()
dt = dct.fit(X_train,y_train)

In [21]:
X_test = np.array(test_df[feature_names])
y_test = np.array(test_df[target_name])

In [22]:
dt.predict(X_test[0, :].reshape(1,-1))

array([0])

In [52]:
pickle.dump(dt, open('./saved_models/dt.p', 'wb'))
dt = pickle.load(open('./saved_models/dt.p', 'rb'))

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rfc = RandomForestClassifier()
rfc = rfc.fit(X_train,y_train)

In [56]:
rfc.predict(X_test[0, :].reshape(1,-1))

array([0])

In [58]:
pickle.dump(rfc, open('./saved_models/rfc.p', 'wb'))
rfc = pickle.load(open('./saved_models/rfc.p', 'rb'))

In [59]:
rfc.predict(X_test[0, :].reshape(1,-1))

array([0])

In [26]:
import tensorflow as tf

In [35]:
nn_model = model= tf.keras.models.Sequential(
            [
                tf.keras.layers.Dense(24,activation='relu'),
                tf.keras.layers.Dense(12,activation='relu'),
                tf.keras.layers.Dense(12,activation='relu'),
                tf.keras.layers.Dense(12,activation='relu'),
                tf.keras.layers.Dense(12,activation='relu'),
                tf.keras.layers.Dense(1),
                tf.keras.layers.Activation(tf.nn.sigmoid),
            ])

In [36]:
nn_model.compile(optimizer="Adam", loss='binary_crossentropy', metrics=['accuracy'])

In [37]:
nn_model.fit(X_train, y_train, batch_size=64, epochs=20, shuffle=True)

Epoch 1/20
407/407 [==============================] - 0s 469us/step - loss: 5.4162 - accuracy: 0.7415
Epoch 2/20
407/407 [==============================] - 0s 403us/step - loss: 0.6115 - accuracy: 0.7920
Epoch 3/20
407/407 [==============================] - 0s 434us/step - loss: 0.7552 - accuracy: 0.7947
Epoch 4/20
407/407 [==============================] - 0s 449us/step - loss: 0.5762 - accuracy: 0.7896
Epoch 5/20
407/407 [==============================] - 0s 403us/step - loss: 1.0686 - accuracy: 0.7889
Epoch 6/20
407/407 [==============================] - 0s 398us/step - loss: 0.7514 - accuracy: 0.7799
Epoch 7/20
407/407 [==============================] - 0s 397us/step - loss: 0.4342 - accuracy: 0.7974
Epoch 8/20
407/407 [==============================] - 0s 399us/step - loss: 0.6007 - accuracy: 0.7939
Epoch 9/20
407/407 [==============================] - 0s 400us/step - loss: 0.4264 - accuracy: 0.7963
Epoch 10/20
407/407 [==============================] - 0s 399us/step - loss: 0.414

In [42]:
nn_model.save('./saved_models/nn.h5',overwrite=True)

In [43]:
nn_model = tf.keras.models.load_model('./saved_models/nn.h5')

In [60]:
nn_model.predict(X_test[0, :].reshape(1,-1))

array([[0.2322611]], dtype=float32)