In [1]:
### Colab define cell
FOLDER_PATH = '/content/gdrive/MyDrive/Counterfactual-prototype-main/LORE/LORE-master'

try:
    import google.colab
    RUNNING_ON_COLAB = True
except: 
    RUNNING_ON_COLAB = False

if RUNNING_ON_COLAB: 
    import sys
    from google.colab import drive
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials 
    drive.mount('/content/gdrive', force_remount=True)
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    gdrive = GoogleDrive(gauth)
    sys.path.append(FOLDER_PATH)

In [3]:
from utils.prediction import PredictionTypeWrapper, PredictionTypeWrapper, generate_local_predictions, wrap_information
from lore import LOREWrapper
from utils import load

import tensorflow as tf
import numpy as np
import pandas as pd

### Set random seed
seed = 123
tf.random.set_seed(seed)
np.random.seed(seed)

In [4]:
### Load data
dataset = load.SelectableDataset.Diabetes
data, balanced_data, X, Y, encoder, scaler, n_features, n_classes, feature_names, target_name = load.load_dataset(dataset)
X_train, Y_train, X_test, Y_test, X_validation, Y_validation = load.load_training_data(dataset)
model = load.load_trained_model_for_dataset(dataset)

Loaded model from disk


2021-07-18 03:58:35.313444: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-18 03:58:35.339773: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-18 03:58:35.340034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.695GHz coreCount: 16 deviceMemorySize: 7.92GiB deviceMemoryBandwidth: 238.66GiB/s
2021-07-18 03:58:35.340059: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-18 03:58:35.343284: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-18 03:58:35.343322: I tensorflow/stream_executor/pla

In [5]:

diabetes_feature_range = (X_train.min(axis=0), X_train.max(axis=0))
# store all information 
local_data_dict = generate_local_predictions( X_test, Y_test, model, scaler, encoder )
# sorting by different conditions
true_positives,true_negatives, false_positives, false_negatives = wrap_information( local_data_dict )
# get all prediction types
all_predictions = PredictionTypeWrapper(true_positives,true_negatives, false_positives, false_negatives)

2021-07-18 03:58:52.134535: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-18 03:58:52.153768: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199995000 Hz
2021-07-18 03:58:52.228765: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-18 03:58:52.266882: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-07-18 03:58:52.266917: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support


InternalError:  Blas xGEMM launch failed : a.shape=[1,32,8], b.shape=[1,8,12], m=32, n=12, k=8
	 [[node model_h5_N12/dense_293/MatMul (defined at home/jrhs/Documents/GitHub/Counterfactual-benchmark/utils/prediction.py:42) ]] [Op:__inference_predict_function_294]

Function call stack:
predict_function


In [ ]:
lore_wrapper = LOREWrapper.LOREWarpper(model)

In [ ]:
from lore.prepare_dataset import prepare_diabetes_dataset

In [ ]:
diabetes_dataset = prepare_diabetes_dataset('./datasets/diabetes.csv')

In [ ]:
X2E = X_test
y2E = lore_wrapper.predict(X2E).flatten()
y2E = np.asarray([diabetes_dataset['possible_outcomes'][i] for i in y2E])

In [ ]:
(lore_wrapper.predict(X2E).flatten() > .5).astype(int)

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [ ]:
print(diabetes_dataset['label_encoder'][diabetes_dataset['class_name']].classes_)
print(diabetes_dataset['possible_outcomes'])

[0 1]
[1, 0]


In [ ]:
idx_record2explain = 0

In [ ]:
import lore

from lore.prepare_dataset import *
from lore.neighbor_generator import *

In [ ]:
# For storing the debuggin information
class debug_info():
    def __init__(self,):
        pass

In [ ]:
path_data = './lore/datasets/'
explanation, infos = lore.explain(idx_record2explain, X2E, diabetes_dataset, lore_wrapper,
                                  ng_function=genetic_neighborhood,
                                  discrete_use_probabilities=True,
                                  continuous_function_estimation=False,
                                  returns_infos=True,
                                  path=path_data, sep=';', log=False, debug_info=debug_info)

X shape is:
(8,)
Input X Shape
(80, 8)


KeyboardInterrupt: 

In [ ]:
debug_info.cmd

'lore/yadt/dTcmd -fd ./lore/datasets/diabetes.data -fm ./lore/datasets/diabetes.names -sep ; -d ./lore/datasets/diabetes.dot'

In [ ]:
debug_info.cmd_output

b'YaDT version 2.1.0 (c) S. Ruggieri 2002-2018\nReading text data\n + atts: 8 class: 1 weight: 0 rows: 971\n + load time: 0.001324 secs (37.08 MiB/s, 733.38 K rows/s)\n + indexing ...there must be at least two class values\n'

In [ ]:
debug_info.tree_filename

'./lore/datasets/diabetes.dot'

In [ ]:
import networkx as nx


In [ ]:
debug_info.dfZ_1

Outcome  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0         0            0        0              0              0        1   
1         0            0        0              0              0        0   
2         0            0        0              0              0        0   
3         0            0        0              0              0        0   
4         0            0        0              0              0        0   
..      ...          ...      ...            ...            ...      ...   
75        0            0        0              0              0        0   
76        0            0        0              0              0        0   
77        0            0        0              0              0        0   
78        0            0        0              0              0        0   
79        0            0        0              0              0        0   

         BMI  DiabetesPedigreeFunction  Age  
0   0.448584                  0.134047    0  
1   0.645306                  0.084368    0  
2   0.441133                  0.047966    0  
3   0.487332                  0.271520    0  
4   0.439642                  0.231692    0  
..       ...                       ...  ...  
75  0.530551                  0.125482    0  
76  0.566319                  0.252248    0  
77  0.326379                  0.107495    0  
78  0.527571                  0.195717    0  
79  0.448584                  0.113062    0  

[80 rows x 9 columns]

In [ ]:
nx.drawing.nx_pydot.read_dot(debug_info.tree_filename)


^
Expected {'graph' | 'digraph'}  (at char 0), (line:1, col:1)


TypeError: 'NoneType' object is not subscriptable

In [ ]:
lore_wrapper.predict(debug_info.dfZ_1[0])

KeyError: 0

In [ ]:
lore_wrapper.predict(X2E[0:1])

array([[0.9535943]], dtype=float32)

In [ ]:
Z = cPickle.loads(cPickle.dumps(X2E))

In [ ]:
Z.shape

(80, 8)

In [ ]:
x = Z[idx_record2explain]

In [ ]:
x

array([0.05882353, 0.94974874, 0.49180328, 0.23232323, 1.        ,
       0.4485842 , 0.13404711, 0.74509804])

In [ ]:
lore_wrapper.predict(x)

ValueError: in user code:

    /home/jrhs/.pyenv/versions/3.8.11/envs/tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1569 predict_function  *
        return step_function(self, iterator)
    /home/jrhs/Documents/GitHub/Counterfactual-benchmark/lore/LOREWrapper.py:11 call  *
        out = self.model(x)
    /home/jrhs/.pyenv/versions/3.8.11/envs/tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1013 __call__  **
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/jrhs/.pyenv/versions/3.8.11/envs/tf/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:251 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer model_h5_N12 is incompatible with the layer: expected axis -1 of input shape to have value 8 but received input with shape (None, 1)


In [ ]:
diabetes_dataset['columns']

['Outcome',
 'Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']